// src/pages/post-detail/PostDetail.jsx
import React, { useContext, useState } from "react";
import { useParams } from "react-router";
import { Link } from "react-router-dom";
import { DatabaseContext } from "../../context/Database";

import CommentBox from "../../components/comment-box/CommentBox";
import "./PostDetail.scss";

const PostDetail = () => {
  const { postId } = useParams();
  const { database } = useContext(DatabaseContext);

  let thisDatabase = database.filter((data) => data.id === Number(postId))[0];

  const { title, summary, img, comments } = thisDatabase;

  const [comment, setComment] = useState({
    user: "Joe Doew",
    comment: "",
  });

  const getFormData = (e) => {
    setComment({
      ...comment,
      [e.target.name]: e.target.value,
    });
  };

  const submitedForm = async (e) => {
    e.preventDefault();
    document.getElementById("comment-input").value = "";
    comments.push(comment);
    setComment({
      user: "Joe Doew",
      comment: "",
    });
  };

  let backImg = {
    backgroundImage: `url('${img}')`,
  };
  return (
    <section>
      <article className="post-header" style={backImg}>
        <div className="post-header-container">
          <div className="return-options">
            <Link to="/posts">
              <span className="material-icons">arrow_back_ios</span> View Posts
            </Link>
          </div>
          <div className="post-header-title">
            <h2>{title}</h2>
          </div>
        </div>
      </article>
      <article className="post-summary">
        <div className="post-summary-container">
          <div className="summary">
            <p>{summary}</p>
          </div>
        </div>
      </article>
      <article className="post-comments">
        <div className="post-comments-title">
          <h3>Comments</h3>
        </div>
        <div className="comments-section">
          {comments.map((comment, idx) => (
            <div key={idx} className="this-comment-box">
              <CommentBox commentData={comment} />
            </div>
          ))}
        </div>
        <div className="comment-form">
          <form>
            <div className="form-col">
              <textarea
                name="comment"
                id="comment-input"
                rows="0"
                placeholder="Write a comment"
                onChange={getFormData}
              ></textarea>
            </div>
            <div className="form-col">
              <button
                onClick={(e) => submitedForm(e)}
                type="button"
                className="submit-button"
              >
                Add
              </button>
            </div>
          </form>
        </div>
      </article>
    </section>
  );
};

export default PostDetail;

// src/app/pages/post-detail/post-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Post } from 'src/app/interfaces/post';
import { DatabaseService } from '../../services/database.service';

@Component({
  selector: 'app-post-detail',
  templateUrl: './post-detail.component.html',
  styleUrls: ['./post-detail.component.scss']
})
export class PostDetailComponent implements OnInit {

  public idObject: number;
  public thisDatabase: Post;
  public invalidForm = false;
  public commentsForm = this.fb.group({
    user: [''],
    comment: ['', Validators.required]
  });

  constructor(private route: ActivatedRoute, private databaseService: DatabaseService, private fb: FormBuilder) {
    this.route.params.subscribe(res => this.idObject = Number(res.id));
    this.thisDatabase = this.databaseService.database.filter(data => data.id === this.idObject)[0];
  }

  ngOnInit(): void {
  }
  public addComment(): void {
    if ( this.commentsForm.invalid ) {
      this.invalidForm = true;
      return;
    }
    this.invalidForm = false;
    this.commentsForm.value.user = 'Joe Doe';
    this.thisDatabase.comments.push(this.commentsForm.value);
    this.commentsForm.reset();
  }
}

<section class="animate__animated animate__fadeIn">
    <article class="post-header" [ngStyle]="{'background-image': 'url('+thisDatabase.img+')'}">
        <div class="post-header-container">
            <div class="return-options">
                <a routerLink="/posts"><span class="material-icons">arrow_back_ios</span> View Posts</a>
            </div>
            <div class="post-header-title">
                <h2>{{ thisDatabase.title }}</h2>
            </div>
        </div>
    </article>
    <article class="post-summary">
        <div class="post-summary-container">
            <div class="summary">
                <p>
                    {{ thisDatabase.summary }}
                </p>
            </div>
        </div>
    </article>
    <article class="post-comments">
        <div class="post-comments-title">
            <h3>Comments</h3>
        </div>
        <div class="comments-section">
            <div class="this-comment-box" *ngFor="let comment of thisDatabase.comments">
                <app-comment-box [thisComment]="comment"></app-comment-box>
            </div>
        </div>
        <div class="comment-form">
            <form autocomplete="false" [formGroup]="commentsForm" (ngSubmit)="addComment()">
                <div class="form-col">
                    <textarea name="comment" [ngClass]="{invalid: invalidForm}" id="comment-input" rows="1" placeholder="write a comment" formControlName="comment"></textarea>
                </div>
                <div class="form-col">
                    <button type="submit" class="submit-button">Add</button>
                </div>
            </form>
        </div>
    </article>
</section>
