// src/components/category-selector/CategorySelector.jsx
import React, { useState, useContext } from "react";
import { DatabaseContext } from "../../context/Database";
import "./CategorySelector.scss";

const CategorySelector = () => {
  const [stateAll, setStateAll] = useState(true);
  const [stateTravel, setStateTravel] = useState(false);
  const [stateLifestyle, setStateLifestyle] = useState(false);
  const [stateBusiness, setStateBusiness] = useState(false);
  const [stateFood, setStateFood] = useState(false);
  const [stateWork, setStateWork] = useState(false);

  const { category, setCategory } = useContext(DatabaseContext);

  // setUpDatabase(database);

  const filterDBBy = (selector) => {
    setCategory(selector);
    setActiveItem(selector);
  };

  const setActiveItem = (value) => {
    switch (value) {
      case "All": {
        setStateAll(true);
        setStateTravel(false);
        setStateLifestyle(false);
        setStateBusiness(false);
        setStateFood(false);
        setStateWork(false);
        return;
      }
      case "Travel": {
        setStateAll(false);
        setStateTravel(true);
        setStateLifestyle(false);
        setStateBusiness(false);
        setStateFood(false);
        setStateWork(false);
        return;
      }
      case "Lifestyle": {
        setStateAll(false);
        setStateTravel(false);
        setStateLifestyle(true);
        setStateBusiness(false);
        setStateFood(false);
        setStateWork(false);
        return;
      }
      case "Business": {
        setStateAll(false);
        setStateTravel(false);
        setStateLifestyle(false);
        setStateBusiness(true);
        setStateFood(false);
        setStateWork(false);
        return;
      }
      case "Food": {
        setStateAll(false);
        setStateTravel(false);
        setStateLifestyle(false);
        setStateBusiness(false);
        setStateFood(true);
        setStateWork(false);
        return;
      }
      case "Work": {
        setStateAll(false);
        setStateTravel(false);
        setStateLifestyle(false);
        setStateBusiness(false);
        setStateFood(false);
        setStateWork(true);
        return;
      }
      default: {
        break;
      }
    }
  };

  return (
    <section className="category-selector">
      <article className="category-selector-container">
        <div className="category-selector-menu">
          <ul>
            <li
              onClick={() => filterDBBy("All")}
              className={`category-selector-option ${stateAll ? "active" : ""}`}
            >
              All
            </li>
            <li
              onClick={() => filterDBBy("Travel")}
              className={`category-selector-option ${
                stateTravel ? "active" : ""
              }`}
            >
              Travel
            </li>
            <li
              onClick={() => filterDBBy("Lifestyle")}
              className={`category-selector-option ${
                stateLifestyle ? "active" : ""
              }`}
            >
              Lifestyle
            </li>
            <li
              onClick={() => filterDBBy("Business")}
              className={`category-selector-option ${
                stateBusiness ? "active" : ""
              }`}
            >
              Business
            </li>
            <li
              onClick={() => filterDBBy("Food")}
              className={`category-selector-option ${
                stateFood ? "active" : ""
              }`}
            >
              Food
            </li>
            <li
              onClick={() => filterDBBy("Work")}
              className={`category-selector-option ${
                stateWork ? "active" : ""
              }`}
            >
              Work
            </li>
          </ul>
        </div>
      </article>
    </section>
  );
};

export default CategorySelector;

// src/app/components/category-selector/category-selector.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { DatabaseService } from '../../services/database.service';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-category-selector',
  templateUrl: './category-selector.component.html',
  styleUrls: ['./category-selector.component.scss']
})
export class CategorySelectorComponent implements OnInit {

  @Output() filter = new EventEmitter();

  public allSelected = true;
  public TravelSelected = false;
  public LifestyleSelected = false;
  public BusinessSelected = false;
  public FoodSelected = false;
  public WorkSelected = false;

  public filteredDb: any[];

  constructor(private databaseService: DatabaseService) { }

  ngOnInit(): void {
  }

  filterDBBy( value: string ): void {
    if(value !== 'All') {
      this.filteredDb = this.databaseService.database.filter(arr => arr.category === value);
    } else {
      this.filteredDb = this.databaseService.database;
    }
    this.filter.emit(this.filteredDb);
    this.setActiveItem(value);
  }

  private setActiveItem(value: string): void {
    switch ( value ) {
      case 'All': {
        this.allSelected = true;
        this.TravelSelected = false;
        this.LifestyleSelected = false;
        this.BusinessSelected = false;
        this.FoodSelected = false;
        this.WorkSelected = false;
        break;
      }
      case 'Travel': {
        this.TravelSelected = true;
        this.allSelected = false;
        this.LifestyleSelected = false;
        this.BusinessSelected = false;
        this.FoodSelected = false;
        this.WorkSelected = false;
        break;
      }
      case 'Lifestyle': {
        this.LifestyleSelected = true;
        this.TravelSelected = false;
        this.allSelected = false;
        this.BusinessSelected = false;
        this.FoodSelected = false;
        this.WorkSelected = false;
        break;
      }
      case 'Business': {
        this.BusinessSelected = true;
        this.TravelSelected = false;
        this.LifestyleSelected = false;
        this.allSelected = false;
        this.FoodSelected = false;
        this.WorkSelected = false;
        break;
      }
      case 'Food': {
        this.FoodSelected = true;
        this.TravelSelected = false;
        this.LifestyleSelected = false;
        this.BusinessSelected = false;
        this.allSelected = false;
        this.WorkSelected = false;
        break;
      }
      case 'Work': {
        this.WorkSelected = true;
        this.TravelSelected = false;
        this.LifestyleSelected = false;
        this.BusinessSelected = false;
        this.FoodSelected = false;
        this.allSelected = false;
        break;
      }

    }
  }

}

<section class="category-selector animate__animated animate__fadeIn">
    <article class="category-selector-container">
        <div class="category-selector-menu">
            <ul>
                <li [ngClass]="{'active': allSelected}" (click)="filterDBBy('All')" class="category-selector-option">All</li>
                <li [ngClass]="{'active': TravelSelected}" (click)="filterDBBy('Travel')" class="category-selector-option">Travel</li>
                <li [ngClass]="{'active': LifestyleSelected}" (click)="filterDBBy('Lifestyle')" class="category-selector-option">Lifestyle</li>
                <li [ngClass]="{'active': BusinessSelected}" (click)="filterDBBy('Business')" class="category-selector-option">Business</li>
                <li [ngClass]="{'active': FoodSelected}" (click)="filterDBBy('Food')" class="category-selector-option">Food</li>
                <li [ngClass]="{'active': WorkSelected}" (click)="filterDBBy('Work')" class="category-selector-option last">Work</li>
            </ul>
        </div>
    </article>
</section>
