// src/app/components/add-post/add-post.component.ts
import { Component, OnInit } from '@angular/core';
import { DatabaseService } from '../../services/database.service';
import { FormBuilder, Validators } from '@angular/forms';
import Swal from 'sweetalert2';


@Component({
  selector: 'app-add-post',
  templateUrl: './add-post.component.html',
  styleUrls: ['./add-post.component.scss']
})
export class AddPostComponent implements OnInit {

  public submittedForm = false;
  public submittedFormUpdate = false;
  public invalidForm = false;
  public invalidTitle = false;
  public invalidSummary = false;
  public invalidImg = false;
  public invalidCategory = false;
  public thisId: number;

  public postForm = this.fb.group({
    id: [''],
    title: ['', Validators.required],
    summary: ['', Validators.required],
    comments: [[]],
    img: ['https://source.unsplash.com/random', Validators.required],
    category: ['', Validators.required]
  });

  public postFormUpdate = this.fb.group({
    id: ['', Validators.required],
    title: ['', Validators.required],
    summary: ['', Validators.required],
    comments: [[]],
    img: ['', Validators.required],
    category: ['', Validators.required]
  });

  constructor(private databaseService: DatabaseService, private fb: FormBuilder) {
    this.thisId = this.databaseService.database.length;
  }

  ngOnInit(): void {
    this.databaseService.updateChange.subscribe((value) => {
      this.postFormUpdate = this.fb.group({
        id: [value.id, Validators.required],
        title: [value.title, Validators.required],
        summary: [value.summary, Validators.required],
        comments: [value.comments],
        img: [value.img, Validators.required],
        category: [value.category, Validators.required]
      });
    });
    this.databaseService.dataBaseChange.subscribe((value) => {
      this.thisId = value.length;
    });
  }

  public addPost(): void {
    this.submittedForm = true;
    const thisId = this.thisId + 1;
    if ( this.postForm.invalid) {
      Swal.fire('Error trying to save your post', 'Complete the required fields', 'error');
      return;
    }
    this.postForm.value.id = thisId;
    this.postForm.value.comments = [];
    this.databaseService.database.unshift(this.postForm.value);
    this.databaseService.dataBaseChange.next(this.databaseService.database);
    Swal.fire('Success', 'Your post have been saved', 'success');
    ($('#exampleModal') as any).modal('hide');
    this.submittedForm = false;
  }

  public updatePost(): void {
    this.submittedFormUpdate = true;
    if ( this.postFormUpdate.invalid) {
      Swal.fire('Error trying to update your post', 'Complete the required fields', 'error');
      return;
    }
    this.databaseService.database.map(obj => {
      if (obj.id === this.postFormUpdate.value.id) {
        const replaceIndex = this.databaseService.database.indexOf(obj);
        obj = this.postFormUpdate.value;
        this.databaseService.database[replaceIndex] = obj;
      }
    });
    Swal.fire('Success', 'Your post have been updated', 'success');
    ($('#updateModal') as any).modal('hide');
  }

  public invalidFieldUpdate( field: string ): boolean {
    if ( this.postFormUpdate.get(field).invalid && this.submittedFormUpdate ) {
      return true;
    } else {
      return false;
    }
  }

  public invalidField( field: string ): boolean {
    if ( this.postForm.get(field).invalid && this.submittedForm ) {
      return true;
    } else {
      return false;
    }
  }

}

<!-- Button trigger modal -->
<button type="button" class="btn btn-modal" data-toggle="modal" data-target="#exampleModal">
    <span class="material-icons">
        edit
    </span>
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create post</h5>
            </div>
            <form autocomplete="false" [formGroup]="postForm" (ngSubmit)="addPost()">
                <div class="modal-body">
                    <div class="form-row">
                        <input type="text" placeholder="Title" class="form-control" formControlName="title">
                        <p *ngIf="invalidField('title')" class="text-danger">* This field is required</p>
                    </div>
                    <div class="form-row">
                        <textarea name="summary" class="form-control" id="sumary-form" rows="1" placeholder="Description" formControlName="summary"></textarea>
                        <p *ngIf="invalidField('summary')" class="text-danger">* This field is required</p>
                    </div>
                    <div class="form-row">
                        <select id="inputState" class="form-control" formControlName="category">
                            <option value ="Travel">Travel</option>
                            <option value ="Lifestyle">Lifestyle</option>
                            <option value ="Business">Business</option>
                            <option value ="Food">Food</option>
                            <option value ="Work">Work</option>
                          </select>
                        <p *ngIf="invalidField('category')" class="text-danger">* This field is required</p>
                    </div>
                    <div class="form-row">
                        <input type="text" id="" class="form-control" placeholder="URL of the image" value="https://source.unsplash.com/random" formControlName="img">
                        <p *ngIf="invalidField('img')" class="text-danger">* This field is required</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-canel" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-submit">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Update post</h5>
            </div>
            <form autocomplete="false" [formGroup]="postFormUpdate" (ngSubmit)="updatePost()">
                <div class="modal-body">
                    <div class="form-row">
                        <input type="text" placeholder="Title" class="form-control" id="titleInput" formControlName="title">
                        <p *ngIf="invalidFieldUpdate('title')" class="text-danger">* This field is required</p>
                    </div>
                    <div class="form-row">
                        <textarea name="summary" class="form-control" id="summaryUpdate" rows="6" placeholder="Description" formControlName="summary"></textarea>
                        <p *ngIf="invalidFieldUpdate('summary')" class="text-danger">* This field is required</p>
                    </div>
                    <div class="form-row">
                        <select id="categoryInput" class="form-control" formControlName="category">
                            <option value ="Travel">Travel</option>
                            <option value ="Lifestyle">Lifestyle</option>
                            <option value ="Business">Business</option>
                            <option value ="Food">Food</option>
                            <option value ="Work">Work</option>
                          </select>
                        <p *ngIf="invalidFieldUpdate('category')" class="text-danger">* This field is required</p>
                    </div>
                    <div class="form-row">
                        <input type="text" id="imgInput" class="form-control" placeholder="URL of the image" formControlName="img">
                        <p *ngIf="invalidFieldUpdate('img')" class="text-danger">* This field is required</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-canel" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-submit">Update Post</button>
                </div>
            </form>
        </div>
    </div>
</div>

// src/components/add-post/AddPost.jsx
import React, { useState, useContext } from "react";
import { Modal, Button, Form } from "react-bootstrap";
import { DatabaseContext } from "../../context/Database";
import Swal from "sweetalert2";
import "./AddPost.scss";

const AddPost = () => {
  const { database, setDatabase } = useContext(DatabaseContext);

  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  const [create, setCreate] = useState({
    id: 10,
    title: "",
    summary: "",
    category: "Travel",
    img: "https://source.unsplash.com/random",
    comments: [],
  });

  const getFormData = (e) => {
    setCreate({
      ...create,
      [e.target.name]: e.target.value,
    });
  };

  const createElement = async () => {
    let thisDb = database.map((data) => data);
    create.id = thisDb.length + 1;
    await thisDb.unshift(create);
    setDatabase(thisDb);
    handleClose();
    Swal.fire("Success", "Your post have been updated", "success");
  };

  return (
    <>
      <button type="button" className="btn btn-modal" onClick={handleShow}>
        <span className="material-icons">edit</span>
      </button>

      {/* ADD MODAL */}
      <Modal show={show} onHide={handleClose}>
        <Modal.Header>
          <Modal.Title>
            <h5>Create post</h5>{" "}
          </Modal.Title>
        </Modal.Header>

        <Form>
          <Modal.Body>
            <Form.Group controlId="exampleForm.ControlInput1">
              <Form.Control
                onChange={getFormData}
                name="title"
                type="text"
                placeholder="Title"
              />
            </Form.Group>

            <Form.Group controlId="exampleForm.ControlTextarea1">
              <Form.Control
                onChange={getFormData}
                name="summary"
                as="textarea"
                rows={1}
                placeholder="Description"
              />
            </Form.Group>

            <Form.Group controlId="exampleForm.ControlSelect1">
              <Form.Control onChange={getFormData} name="category" as="select">
                <option value="Travel">Travel</option>
                <option value="Lifestyle">Lifestyle</option>
                <option value="Business">Business</option>
                <option value="Food">Food</option>
                <option value="Work">Work</option>
              </Form.Control>
            </Form.Group>

            <Form.Group controlId="exampleForm.ControlInput1">
              <Form.Control
                onChange={getFormData}
                name="img"
                type="text"
                placeholder="image url"
                value="https://source.unsplash.com/random"
              />
            </Form.Group>
          </Modal.Body>

          <Modal.Footer>
            <Button variant="Light" onClick={handleClose}>
              Close
            </Button>
            <Button
              variant="default"
              className="btn-submit"
              onClick={createElement}
            >
              Save Changes
            </Button>
          </Modal.Footer>
        </Form>
      </Modal>
    </>
  );
};

export default AddPost;
