// src/components/comment-box/CommentBox.jsx
import React from "react";
import "./CommentBox.scss";

const CommentBox = (props) => {
  const { user, comment } = props.commentData;
  return (
    <div className="comment-box">
      <div className="comment">
        <div className="user-img">
          <p>
            <span className="material-icons">person_pin</span>
          </p>
        </div>
        <div className="comment-body">
          <div className="comment-user">
            <h3>{user}</h3>
          </div>
          <div className="comment-text">
            <p>{comment}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CommentBox;

// src/app/components/comment-box/comment-box.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommentInterface } from '../../interfaces/comment';

@Component({
  selector: 'app-comment-box',
  templateUrl: './comment-box.component.html',
  styleUrls: ['./comment-box.component.scss']
})
export class CommentBoxComponent implements OnInit {

  @Input() thisComment: CommentInterface;
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="comment-box">
    <div class="comment">
        <div class="user-img">
            <p>
                <span class="material-icons">
                    person_pin
                </span>
            </p>
        </div>
        <div class="comment-body">
            <div class="comment-user">
                <h3>{{ thisComment.user }}</h3>
            </div>
            <div class="comment-text">
                <p>
                    {{ thisComment.comment }}
                </p>
            </div>
        </div>
    </div>
</div>
